[versions]
androidGradlePlugin = "8.12.0-alpha03"
annotation = "1.9.1"
json = "20250517"
kotlin = "2.2.0-RC2"
compose = "1.9.0-alpha04"
lifecycle = "2.9.1"
material3 = "1.4.0-alpha15"
materialKolor = "3.0.0-beta05"
media3 = "1.8.0-alpha01"
room = "2.7.1"
hilt = "2.56.2"
ktor = "3.1.3"
ksp = "2.2.0-RC2-2.0.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
guava = { group = "com.google.guava", name = "guava", version = "33.4.8-jre" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version = "1.10.2" }
concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version = "1.3.0-beta01" }

gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
activity = { group = "androidx.activity", name = "activity-compose", version = "1.12.0-alpha02" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.0" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.3.0-alpha01" }
datastore = { group = "androidx.datastore", name = "datastore-preferences", version = "1.2.0-alpha02" }

compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-animation = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "compose" }
compose-reorderable = { module = "sh.calvin.reorderable:reorderable", version = "2.4.3" }

squigglyslider = { group = "me.saket.squigglyslider", name = "squigglyslider", version = "1.0.0" }

viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }

coil = { group = "io.coil-kt", name = "coil-compose", version = "2.7.0" }

shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version = "1.3.3" }

palette = { group = "androidx.palette", name = "palette", version = "1.0.0" }

media3 = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-okhttp = { group = "androidx.media3", name = "media3-datasource-okhttp", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

apache-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.17.0" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor_client_cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

json = { module = "org.json:json", version.ref = "json" }

brotli = { group = "org.brotli", name = "dec", version = "0.1.2" }

desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }

junit = { group = "junit", name = "junit", version = "4.13.2" }

timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }

newpipe-extractor = { group = "com.github.libre-tube", name = "NewPipeExtractor", version = "bcb7705" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
